name: e2e-k8s

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    paths:
      - 'pkg/query-service/**'
      - 'frontend/**'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo hello
