name: remove-label

on:
  pull_request:
    types: [synchronize]
    paths:
      - 'pkg/query-service/**'
      - 'frontend/**'

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Remove label
        uses: buildsville/add-remove-label@v1
        with:
          label: ok-to-test
          type: remove
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

